name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: install
        run: npm install

      - name: test
        run: npm test

      - name: lint
        run: npm run lint
